### ISSUE TITLE
Add to cargo "Third-party cargo subcommands" page

### ISSUE THREAD

**Issue by Michael-F-Bryan** [kstep/cargo-pkgbuild#1]
This looks like a pretty useful little cargo subcommand for those who use Arch and want to have something installed globally. Would you be okay with me adding it to the [subcommands][1] page on the cargo wiki?

[1]: https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands

**Comment by kstep** [comment]
Sure, feel free to mention it anywhere you want!

**Comment by Michael-F-Bryan** [comment]
Done
