### ISSUE TITLE
Rust package guidelines

### ISSUE THREAD

**Issue by frol** [kstep/cargo-pkgbuild#6]
There is a wiki https://wiki.archlinux.org/index.php/Rust_package_guidelines

**Comment by MadeOfMagicAndWires** [comment]
Separating building from installing is most important of the one there, `package()` really should only be moving existing files from `src` to `pkgdir`.

**Comment by alerque** [comment]
The guidelines have expanded from 2 years ago as well, `prepare()` and `check()` functions are recommended. The PKGBUILDs generated by this tool are not even close to following these guidelines.

Would you accept a PR that fixed some of the major issues at least? It's not encouraging to see that this has gone untouched for years. I can contribute but I don't want to bother if they won't be accepted.

**Comment by kstep** [comment]
I lost interest in the package a long time ago, but if you are willing to contribute, I'll be happy to accept your PRs.

**Comment by kstep** [comment]
I closed this issue as it was addressed in #8. If you still have any problems with it, feel free to reopen the issue.
